### ISSUE TITLE
Error on import

### ISSUE THREAD

**Issue by messer979** [deepstartup/WHOAPIdata#1]
After installing fresh, getting this error after import:

    import apidatawho as who
    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/home/cmesser/who/venv/lib/python3.6/site-packages/apidatawho/__init__.py", line 1, in <module>
    from .apidatawho import *
    File "/home/cmesser/who/venv/lib/python3.6/site-packages/apidatawho/apidatawho.py", line 20, in <module>
    APIParam=getAPIParams()
    File "/home/cmesser/who/venv/lib/python3.6/site-packages/apidatawho/apidatawho.py", line 17, in getAPIParams
    with open(os.path.dirname(os.path.abspath('__file__')).replace('\\', '/')+'/apidatawho/config.yml') as info:
    FileNotFoundError: [Errno 2] No such file or directory: '/home/cmesser/who/apidatawho/config.yml'

**Comment by ethercod3** [comment]
Same. After 2 years. Bruh.
